name: Update gist with latest YouTube videos
on:
  schedule:
    - cron: "5 * * * *"
  
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: "Pip install"
        run: pip install -r requirements.txt

      - name: "Update gist"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: b176663e3f3b2b76a52c4822a6fc8cb9
          CHANNEL_ID: UCPopihIU8LMr6T9FCligVHA
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
        run: python main.py
