name: Update gist with latest YouTube videos
on:
  schedule:
    - cron: "0-59 * * * *"
  
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: "Pip install"
        run: pip install -r requirements.txt

      - name: "Update gist"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: dc3d0f7a3cd13207770a4debbb902d1d
          CHANNEL_ID: UCrVWVOBoBu7W-aXbApDEuyQ
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
        run: python main.py
